repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.3 # Use the latest version from the repository
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs
